/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonBase: typeof import('./src/components/button/Base.vue')['default']
    InputBase: typeof import('./src/components/input/Base.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
    Unlock: typeof import('./src/components/Unlock.vue')['default']
  }
}
